### ISSUE TITLE
uds-ewt-documents-dev-normalized.json not found

### ISSUE THREAD

**Issue by jvalinsky** [decompositional-semantics-initiative/decomp#15] opened 2020-09-21 18:17 UTC
When I follow the instructions in the Readme.md to build the Docker container I get the following error:

```shell
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/decomp/decomp/data/2.0/normalized/document/uds-ewt-documents-dev-normalized.json'
```

commands run:
```shell
git clone git://github.com/decompositional-semantics-initiative/decomp.git
cd decomp
docker build -t decomp .
```

I get the same error by installing the decomp library and trying the following Python code:
```python
from decomp import UDSCorpus

uds = UDSCorpus()
```

I tried to install at the latest release tag instead of using master and it seemed to take longer but gave the same error:
```shell
pip install --user -e git://github.com/decompositional-semantics-initiative/decomp.git@v0.1.3#egg=decomp
```

**Comment by sidsvash26** [comment] 2020-09-21 20:04
I installed decomp on a new anaconda environment using the following commands:
```shell
conda create -n py3.8 python=3.8
source activate py3.8 
conda install pip
pip install --user git+git://github.com/decompositional-semantics-initiative/decomp.git
```

When I import the library in Python as follows:
```python
from decomp import UDSCorpus
uds = UDSCorpus()
``` 
I receive a similar error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sidvash/.local/lib/python3.8/site-packages/decomp/semantics/uds.py", line 222, in __init__
    spl.to_json(sentences_json_path, documents_json_path)
  File "/Users/sidvash/.local/lib/python3.8/site-packages/decomp/semantics/uds.py", line 428, in to_json
    with open(sentences_outfile, 'w') as out:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sidvash/.local/lib/python3.8/site-packages/decomp/data/2.0/normalized/sentence/uds-ewt-sentences-dev-normalized.json'
```

When using 0.1.3 v installation as follows:

```shell
pip install --user -e git://github.com/decompositional-semantics-initiative/decomp.git@v0.1.3#egg=decomp
```
I get a new error when importing UDS:
```python
from decomp import UDSCorpus
uds = UDSCorpus()
```


```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sidvash/src/decomp/decomp/semantics/uds.py", line 88, in __init__
    corp_split = self.__class__.from_json(fpath)
  File "/Users/sidvash/src/decomp/decomp/semantics/uds.py", line 183, in from_json
    graphs_json = json.load(infile)
  File "/anaconda3/envs/py3.8/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/anaconda3/envs/py3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/anaconda3/envs/py3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/anaconda3/envs/py3.8/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 167268161 (char 167268160)
```

My pip and python are both run in anaconda env:
```shell
which -a pip
/anaconda3/envs/py3.8/bin/pip
```

```shell
which -a python
/anaconda3/envs/py3.8/bin/python
```
I'm using Mac Mojave v 10.14.6

**Comment by wgantt** [comment] 2020-09-21 20:28
Thanks @sidsvash26 and @jvalinsky. The issue is that the `document` directory, which stores the serialized document graphs, doesn't exist on first install. This was an error on my part, as I created the document directory locally when adding support for document-level graphs and annotations but forgot that git will not track empty directories. I'll let you know when the fix has been merged.

**Comment by wgantt** [comment] 2020-09-21 20:57
PR is here: https://github.com/decompositional-semantics-initiative/decomp/pull/16/files.

**Comment by aaronstevenwhite** [comment] 2020-09-21 21:25
@jvalinsky can you confirm that this works?

**Comment by jvalinsky** [comment] 2020-09-21 23:00
I can confirm that #16 works in a conda environment and Docker environment. 

Edit: ok weirdly enough everything works fine now when I uninstalled and reinstalled the decomp library.

**Comment by sidsvash26** [comment] 2020-09-22 06:31
This doesn't work for me. I am getting exactly the same error messages that I was getting earlier. I deleted my old conda environment and create a new one using the commands described above. 

@jvalinsky could you describe the conda process that worked for you?

**Comment by wgantt** [comment] 2020-09-22 12:27
@sidsvash26 it should work regardless of the setup method, so I'll investigate that today.

**Comment by jvalinsky** [comment] 2020-09-22 15:02
@sidsvash26 are you installing from master? Aaron pushed the changes to master, the v0.1.3 version does not have the changes. I just tried reinstalling everything and it worked for me both in a conda and a docker environment.

**Comment by aaronstevenwhite** [comment] 2020-09-22 15:31
This really should not be affecting v0.1.3. I don't know what's up there.

**Comment by sidsvash26** [comment] 2020-09-22 19:25
> @sidsvash26 are you installing from master? Aaron pushed the changes to master, the v0.1.3 version does not have the changes. I just tried reinstalling everything and it worked for me both in a conda and a docker environment.

Yes, I installed from master. 
The Master version (decomp-2.0.0a1) gives me the following error as described above:
```
>>> from decomp import UDSCorpus
>>> uds = UDSCorpus()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sidvash/.local/lib/python3.8/site-packages/decomp/semantics/uds.py", line 222, in __init__
    spl.to_json(sentences_json_path, documents_json_path)
  File "/Users/sidvash/.local/lib/python3.8/site-packages/decomp/semantics/uds.py", line 428, in to_json
    with open(sentences_outfile, 'w') as out:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sidvash/.local/lib/python3.8/site-packages/decomp/data/2.0/normalized/sentence/uds-ewt-sentences-dev-normalized.json'
```
I checked the decomp/data directory and found the following files there:
```shell
(cd /Users/sidvash/.local/lib/python3.8/site-packages/decomp/data && ls -l)

total 4384
-rw-r--r--  1 sidvash  staff    20014 Sep 22 15:16 LICENSE
-rw-r--r--  1 sidvash  staff      463 Sep 22 15:16 build.log
-rw-r--r--  1 sidvash  staff  2219492 Sep 22 15:16 ud_ids.json
```

version details:
```shell
pip show decomp
```

```
Name: decomp
Version: 2.0.0a1
Summary: Toolkit for working with Universal                   Decompositional Semantics graphs
Home-page: https://decomp.io/
Author: Aaron Steven White
Author-email: aaron.white@rochester.edu
License: MIT
Location: /Users/sidvash/.local/lib/python3.8/site-packages
Requires: numpy, rdflib, typing, pyparsing, requests, networkx, predpatt, memoized-property, overrides, setuptools
Required-by:
```

Installing v0.1.3 gives me JSON decoding error that I described in the comments before.

**Comment by sidsvash26** [comment] 2020-09-22 20:34
It seems that this issue is with how conda handles different environments. So I'm going to uninstall entire conda and install again to check if that works. Closing the issue for now.

**Comment by sidsvash26** [comment] 2020-09-23 18:39
I installed Anaconda afresh after uninstalling Anaconda completely from my machine. Installed decomp again but still getting the same error:
```python
>>> uds = UDSCorpus()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sidvash/anaconda3/lib/python3.8/site-packages/decomp-2.0.0a1-py3.8.egg/decomp/semantics/uds.py", line 222, in __init__
    spl.to_json(sentences_json_path, documents_json_path)
  File "/Users/sidvash/anaconda3/lib/python3.8/site-packages/decomp-2.0.0a1-py3.8.egg/decomp/semantics/uds.py", line 428, in to_json
    with open(sentences_outfile, 'w') as out:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sidvash/anaconda3/lib/python3.8/site-packages/decomp-2.0.0a1-py3.8.egg/decomp/data/2.0/normalized/sentence/uds-ewt-sentences-dev-normalized.json'
```

It seems the file "uds-ewt-sentences-dev-normalized.json" is found nowhere.

**Comment by sidsvash26** [comment] 2020-09-25 04:51
I think I may have found the issue. I was successfully able to load decomp using a new environment with Python 3.7.0
When installing decomp with Python 3.7.0, I noticed a warning message which might be the issue related to how pip handles installations in the new versions. I'm not sure if this is the main issue but something to check. 

![Screen Shot 2020-09-25 at 12 45 09 AM](https://user-images.githubusercontent.com/10222970/94227686-13a9d400-fec9-11ea-8261-40d98ccb6f08.png)

@jvalinsky can you confirm if you were running decomp on an older Python version?

**Comment by sidsvash26** [comment] 2020-09-25 05:05
Wow. Magically now it runs on a new env with Python 3.8.5 as well!!! 

Although when I run `pip uninstall decomp` on the py3.8 conda env, it is still loading the package in python interpreter. This means that it is using some path outside the environment to run the package. Maybe the one that was installed from 3.7.0? This is confusing.

**Comment by jvalinsky** [comment] 2020-09-25 11:38
@sidsvash26 I was using Python 3.7

**Comment by aaronstevenwhite** [comment] 2020-09-29 22:46
Would someone be willing to make a PR with a note in the README and documentation about the conda issue?

**Comment by jvalinsky** [comment] 2020-09-30 14:50
@aaronstevenwhite I made a PR for conda install issue #17

**Comment by wgantt** [comment] 2020-11-30 13:22
I just encountered this issue again on a fresh install. I feel like the issue must be related to some out-of-date config either in `setup.py` or in `MANIFEST.in` (the latter of which is _definitely_ out of date). `python setup.py install` currently fails to copy _any_ annotations into `site-packages`. I need to read the `setuptools` docs in more depth to determine what specifically needs to be changed.

**Comment by aaronstevenwhite** [comment] 2021-02-24 14:42
This has been fixed by an update to `MANIFEST.in` in #21.

**Closed as completed by aaronstevenwhite** 2021-02-24 14:42 UTC
