### ISSUE TITLE
ValueError: PredPatt was unable to parse the CoNLL you provided. This is likely due to using a version of UD that is incompatible with PredPatt. Use of version 1.2 is suggested.

### ISSUE THREAD

**Issue by Yottaxx** [decompositional-semantics-initiative/decomp#5] opened 2020-03-17 08:27 UTC
this is the code:
from decomp import UDSCorpus
uds = UDSCorpus()

Traceback (most recent call last):
  File "C:\Users\60585\AppData\Roaming\Python\Python36\site-packages\decomp\semantics\predpatt.py", line 82, in from_conll
    for sid, ud_parse in load_conllu(data)}
  File "C:\Users\60585\AppData\Roaming\Python\Python36\site-packages\decomp\semantics\predpatt.py", line 80, in <dictcomp>
    predpatt = {name+'-'+sid.split('_')[1]: PredPatt(ud_parse,
  File "C:\Users\60585\AppData\Roaming\Python\Python36\site-packages\predpatt\util\load.py", line 34, in load_conllu
    if os.path.isfile(filename):
  File "C:\Users\60585\Anaconda3\envs\pytorch\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
ValueError: stat: path too long for Windows

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/60585/PycharmProjects/Design/data.py", line 7, in <module>
    uds = UDSCorpus()
  File "C:\Users\60585\AppData\Roaming\Python\Python36\site-packages\decomp\semantics\uds.py", line 107, in __init__
    name='ewt-'+sname)
  File "C:\Users\60585\AppData\Roaming\Python\Python36\site-packages\decomp\semantics\uds.py", line 158, in from_conll
    predpatt_corpus = PredPattCorpus.from_conll(corpus, name=name)
  File "C:\Users\60585\AppData\Roaming\Python\Python36\site-packages\decomp\semantics\predpatt.py", line 90, in from_conll
    raise ValueError(errmsg)
ValueError: PredPatt was unable to parse the CoNLL you provided. This is likely due to using a version of UD that is incompatible with PredPatt. Use of version 1.2 is suggested.

I've just tried to use your project, but to find this problem.
Are there other versions for you project?
How could I get over this problem

**Comment by ccmaymay** [comment] 2020-03-30 15:46
I got this error on Windows too.  It looks like the problem is actually in the first traceback:

```ValueError: stat: path too long for Windows```

My solution was to switch to Linux, but that might not be an option for everyone.  [It looks like the path limit is 260 characters, and you can edit the registry to relax it](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/), but the issue might be able to be prevented in practice by naming files by their position in a list?

**Comment by jguallar-blasco** [comment] 2020-05-07 19:29
I had the same issue and followed the directions in the link posted by @ccmaymay but I still received the same error as before.

**Comment by aaronstevenwhite** [comment] 2020-09-22 14:54
Can you confirm that this is an issue when using the supplied Docker container or the Windows Subsystem for Linux? If this is indeed an issue raised by the way Windows handles long file names, we can't do too much on our end besides adding more informative error messages and a warning in the docs.

**Comment by rawlins** [comment] 2021-02-23 01:47
Some students in event semantics at JHU this semester hit this; it is happening because UDS passes file contents directly to `load_conllu` in PredPatt. This is supposed to be supported semantics for that function, but the code there first tries to check whether the argument is a filename, which trips a ValueError in `os.stat` on windows in particular (the string is millions of characters long). I opened a PR on the PredPatt repository that *hopefully* fixes this; but I wonder if anyone who knows the code could suggest any workarounds that are UDS-internal and so would be quicker for our students?

**Comment by aaronstevenwhite** [comment] 2021-02-23 15:03
I unfortunately don't have the ability to merge PRs on PredPatt. The most straightforward stopgap is probably to use the docker image.

**Comment by rawlins** [comment] 2021-02-24 14:28
ok, permissions have been worked out and this fix has been merged into PredPatt, so for anyone who has been stuck on this, as long as you update your PredPatt version (may need to uninstall and reinstall using pip) this issue should be at long last resolved!

**Closed as completed by rawlins** 2021-02-24 14:28 UTC
